- name: "Nvidia | Add repository (deb822, Ubuntu >= 22.04)"
  deb822_repository:
    name: "nvidia-repository"
    types: deb
    uris: "{{ nvidia_repo | trim }}"
    suites: "/"
    signed_by: "{{ nvidia_repo_key | trim }}"
    state: "present"
    mode: "0644"
  when: (nvidia_repo | trim | length > 0) and (nvidia_repo_key | trim | length > 0)

- name: "Nvidia Container Toolkit | Add apt repository with key (deb822, Ubuntu >= 22.04)"
  deb822_repository:
    name: "nvidia-container-toolkit"
    types: deb
    uris: "{{ nvidia_container_toolkit_repo_url | trim }}"
    suites: "/"
    signed_by: "{{ nvidia_container_toolkit_signed_by | trim }}"
    state: "present"
    mode: "0644"
  register: nvidia_ctk_repo
  when: nvidia_container_toolkit_install
